version: '3'
services:
  db:
    image: postgres
    ports:
      - 3306:3306
  web:
    build: .
    command: foreman start -f Procfile.dev # bundle exec rails s
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
